# Generated by Django 4.2.7 on 2023-11-22 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0002_userincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userincome.source'),
        ),
    ]
