# Generated by Django 4.2.7 on 2023-11-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0003_alter_income_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
