# Generated by Django 4.2.7 on 2023-11-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0004_alter_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(max_length=266),
        ),
    ]
