# Generated by Django 4.2.7 on 2023-11-11 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountId', models.AutoField(primary_key=True, serialize=False)),
                ('accountName', models.CharField(max_length=255)),
                ('type', models.IntegerField(null=True)),
                ('initialAmount', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('categoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneym.category')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transferId', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('note', models.TextField(null=True)),
                ('fromAccountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='moneym.account')),
                ('toAccountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='moneym.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Income'), (-1, 'Expense')])),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('note', models.TextField(blank=True)),
                ('accountId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moneym.account')),
                ('subcategoryId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moneym.subcategory')),
            ],
        ),
    
    ]
