# Generated by Django 4.2.7 on 2023-11-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Bank Account'), (3, 'Credit Cards')], null=True),
        ),
    ]
