# Generated by Django 4.2.7 on 2023-11-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneym', '0002_alter_account_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategories'},
        ),
    ]
