# Generated by Django 4.2.7 on 2023-11-21 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Cash'), (2, 'Bank Accounts'), (3, 'Credit Cards')], null=True)),
                ('initialAmount', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
