# Generated by Django 4.2.7 on 2023-11-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='initialAmount',
            field=models.IntegerField(),
        ),
    ]
