# Generated by Django 4.2.7 on 2023-11-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_initialamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='initialAmount',
            field=models.IntegerField(default=0),
        ),
    ]
