# Generated by Django 4.2.7 on 2023-11-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_initialamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountName',
            field=models.CharField(default=2, max_length=255),
        ),
    ]
