# Generated by Django 4.2.7 on 2023-11-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_accountname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountName',
            field=models.CharField(max_length=255),
        ),
    ]
