# Generated by Django 4.2.7 on 2023-11-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_accountname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='initialAmount',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
