# Generated by Django 4.2.7 on 2023-11-25 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_remove_account_initialamount_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accountName',
            new_name='account_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
