# Generated by Django 4.2.7 on 2023-11-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-account_name']},
        ),
    ]
