# Generated by Django 4.2.7 on 2023-11-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='categoryId',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.category'),
        ),
    ]
