# Generated by Django 4.2.7 on 2023-11-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_remove_expense_owner_expense_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
    ]
