# Generated by Django 4.2.7 on 2023-11-29 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_expense_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
    ]
